---
--- Clean script generated by Sort static definitions ---
---
---

delete from SS_RAWDATA;
delete from SS_TEMPLATE_DATATYPE;
delete from SS_DATATYPE;
delete from SS_TEMPLATE_CONTENT;
delete from SS_TEMPLATE;
delete from SS_CSV_MAPPING;
delete from SS_CSVSTRUCTURE_FIELD;
delete from SS_CSVSTRUCTURE;
delete from SS_XML_MAPPING;
delete from SS_XMLSTRUCTURE;
delete from SS_SYNTAX_MODEL;

delete from MAC_USER;
delete from MAC_ACCESS_AREA;