/*
 Clean script generated by BarleyDB static definitions
*/
delete from XSS_XRAWDATA;
delete from XSS_XTEMPLATE_DATATYPE;
delete from XSS_XDATATYPE;
delete from XSS_XTEMPLATE_CONTENT;
delete from XSS_XTEMPLATE;
delete from XSS_XCSV_MAPPING;
delete from XSS_XCSVSTRUCTURE_FIELD;
delete from XSS_XCSVSTRUCTURE;
delete from XSS_XXML_MAPPING;
delete from XSS_XXMLSTRUCTURE;
delete from XSS_XSYNTAX_MODEL;
delete from SS_RAWDATA;
delete from SS_TEMPLATE_DATATYPE;
delete from SS_DATATYPE;
delete from SS_TEMPLATE_CONTENT;
delete from SS_TEMPLATE;
delete from SS_CSV_MAPPING;
delete from SS_CSVSTRUCTURE_FIELD;
delete from SS_CSVSTRUCTURE;
delete from SS_XML_MAPPING;
delete from SS_XMLSTRUCTURE;
delete from SS_SYNTAX_MODEL;

delete from ACL_USER;
delete from ACL_ACCESS_AREA;