---
-- #%L
-- Simple Object Relational Framework
-- %%
-- Copyright (C) 2014 Scott Sinclair <scottysinclair@gmail.com>
-- %%
-- All rights reserved.
-- #L%
---
create table MAC_ACCESS_AREA (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  PARENT_ID BIGINT NULL
);

create table MAC_USER (
  ID BIGINT NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);


create table SS_SYNTAX_MODEL (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  SYNTAX_TYPE INTEGER NOT NULL,
  STRUCTURE_TYPE INTEGER NOT NULL,
  USER_ID BIGINT NOT NULL,
  STRUCTURE_ID BIGINT NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

create table SS_XML_MAPPING (
  ID BIGINT NOT NULL,
  TARGET_FIELD_NAME VARCHAR(50) NOT NULL,
  XPATH VARCHAR(50) NOT NULL,
  SYNTAX_MODEL_ID BIGINT NOT NULL,
  SUB_SYNTAX_MODEL_ID BIGINT NULL
);

create table SS_CSV_MAPPING (
  ID BIGINT NOT NULL,
  TARGET_FIELD_NAME VARCHAR(50) NOT NULL,
  COL_INDEX INTEGER NOT NULL,
  SYNTAX_MODEL_ID BIGINT NOT NULL
);

create table SS_XMLSTRUCTURE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
  );

create table SS_CSVSTRUCTURE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

create table SS_CSVSTRUCTURE_FIELD (
  ID BIGINT NOT NULL,
  COL_INDEX INTEGER NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  OPTIONAL INT NOT NULL,
  STRUCTURE_ID BIGINT NOT NULL,
);


create table SS_TEMPLATE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

create table SS_TEMPLATE_CONTENT (
  ID BIGINT NOT NULL,
  TEMPLATE_ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

create table SS_DATATYPE (
  ID BIGINT NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  MODIFIED_AT TIMESTAMP NOT NULL
);

create table SS_TEMPLATE_DATATYPE (
  ID BIGINT NOT NULL,
  TEMPLATE_ID BIGINT NOT NULL,
  DATATYPE_ID BIGINT NOT NULL
);


alter table MAC_ACCESS_AREA add CONSTRAINT PK_ACCESS_AREA PRIMARY KEY (ID);
alter table MAC_USER add CONSTRAINT PK_USER PRIMARY KEY (ID);
alter table SS_SYNTAX_MODEL add CONSTRAINT PK_SYNTAX_MODEL PRIMARY KEY (ID);
alter table SS_XML_MAPPING add CONSTRAINT PK_XML_MAPPING PRIMARY KEY (ID);
alter table SS_CSV_MAPPING add CONSTRAINT PK_CSV_MAPPING PRIMARY KEY (ID);
alter table SS_XMLSTRUCTURE add CONSTRAINT PK_XMLSTRUCTURE PRIMARY KEY (ID);
alter table SS_CSVSTRUCTURE add CONSTRAINT PK_CSVSTRUCTURE PRIMARY KEY (ID);
alter table SS_CSVSTRUCTURE_FIELD add CONSTRAINT PK_CSVSTRUCTURE_FIELD PRIMARY KEY (ID);
alter table SS_TEMPLATE add CONSTRAINT PK_TEMPLATE PRIMARY KEY (ID);
alter table SS_TEMPLATE_CONTENT add CONSTRAINT PK_TEMPLATE_CONTENT PRIMARY KEY (ID);

alter table SS_DATATYPE add CONSTRAINT PK_DATATYPE PRIMARY KEY (ID);
alter table SS_TEMPLATE_DATATYPE add CONSTRAINT PK_TEMPLATE_DATATYPE PRIMARY KEY (TEMPLATE_ID, DATATYPE_ID);

alter table MAC_ACCESS_AREA add CONSTRAINT FK_ACCESS_AREA_PARENT FOREIGN KEY (PARENT_ID) REFERENCES MAC_ACCESS_AREA(ID);
alter table SS_SYNTAX_MODEL add CONSTRAINT FK_SYNTAX_MODEL_USER FOREIGN KEY(USER_ID) REFERENCES MAC_USER(ID);
alter table SS_XML_MAPPING add CONSTRAINT FK_XML_MAPPING_SYNTAX_MODEL FOREIGN KEY(SYNTAX_MODEL_ID) REFERENCES SS_SYNTAX_MODEL(ID);
alter table SS_XML_MAPPING add CONSTRAINT FK_XML_MAPPING_SUB_SYNTAX_MODEL FOREIGN KEY(SUB_SYNTAX_MODEL_ID) REFERENCES SS_SYNTAX_MODEL(ID);
alter table SS_CSV_MAPPING add CONSTRAINT FK_CSV_MAPPING_SYNTAX_MODEL FOREIGN KEY(SYNTAX_MODEL_ID) REFERENCES SS_SYNTAX_MODEL(ID);
alter table SS_CSVSTRUCTURE_FIELD add CONSTRAINT FK_CSVSTRUCTURE_FIELD_STR FOREIGN KEY(STRUCTURE_ID) REFERENCES SS_CSVSTRUCTURE(ID);
alter table SS_TEMPLATE_CONTENT add CONSTRAINT FK_TC_TEMPLATE FOREIGN KEY(TEMPLATE_ID) REFERENCES SS_TEMPLATE(ID);
alter table SS_TEMPLATE_DATATYPE add CONSTRAINT FK_TD_TEMPLATE FOREIGN KEY(TEMPLATE_ID) REFERENCES SS_TEMPLATE(ID);
alter table SS_TEMPLATE_DATATYPE add CONSTRAINT FK_TD_DATATYPE FOREIGN KEY(DATATYPE_ID) REFERENCES SS_DATATYPE(ID);


